###########################################################################
# Docker Compose File
###########################################################################
#
# Your Docker Compose file spins up your application's environment.
# It defines all of the services, network links and volumes to
# be used by your application. Modify this file as required.
#
version: '2'
services:
  web:
    build: .
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - "8886:80"
    

